version: '3'

services:
  vassago:
    container_name: vassago
    build:
      context: ./
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ProxyONE001
      MONGO_INITDB_DATABASE: banco
    volumes:
      - mongodb_data:/data/db
      - ./application/static/js/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

